# Generated by Django 5.0.6 on 2024-07-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"ordering": ["-timestamp"]},
        ),
    ]
