# Generated by Django 5.0.6 on 2024-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_alter_rating_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="active_update_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
