# Generated by Django 5.0.6 on 2024-07-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0003_rating_active_update_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={},
        ),
    ]
