# Generated by Django 5.0.6 on 2024-07-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
