# Generated by Django 5.0.6 on 2024-07-24 08:29

import exports.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=exports.models.export_file_handler
            ),
        ),
        migrations.AlterField(
            model_name="export",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
