# Generated by Django 5.0.6 on 2024-07-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
