# Generated by Django 5.0.6 on 2024-07-19 09:49

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="handle",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from=["title", "release_date"],
            ),
        ),
    ]
