# Generated by Django 5.0.6 on 2024-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_remove_movie_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.CharField(max_length=255),
        ),
    ]
